---
- name: Restore factcheck{1,2}.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) 방화벽 서비스 삭제 - http(80/tcp)
      ansible.posix.firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: true

    - name: 2) 서비스 종료 - firewalld, httpd
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      ignore_errors: true
      loop:
        - firewalld
        - httpd

    - name: 3) 서비스 설정 삭제 - /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제 - httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
