---
- name: Restore playbook.yml
  hosts: all
  gather_facts: false
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: 블럭을 사용한 처리 예제
      block:
      - name: 1) 서비스 중지 - {{ db_service }}
        ansible.builtin.systemd:
          name: "{{ db_service }}"
          state: stopped
          enabled: false
      rescue:
      - name: 2) 서비스 중지 에러
        ansible.builtin.debug:
          msg: 서비스가 이미 제거됨
      always:
      - name: 3) 패키지 삭제 - httpd, mariadb, mariadb-server
        ansible.builtin.dnf:
          name:
            - "{{ web_package }}"
            - "{{ db_package }}"
          state: absent
