---
- name: Restore createusers.yml
  hosts: devservers
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 1) 사용자 삭제
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      loop: "{{ newusers }}"
